# Generated by Django 5.0.3 on 2024-03-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0003_highlite_new_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlite',
            name='image_titleHighlights',
            field=models.ImageField(blank=True, upload_to='image', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image_titleNews',
            field=models.ImageField(blank=True, upload_to='image', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image_titlePodcasts',
            field=models.ImageField(blank=True, upload_to='image', verbose_name='Превью'),
        ),
    ]
